server:
  servlet:
    context-path: /chat-app
  port: 9080
tourism:
  service:
    name: CHAT-APP
logging:
  level:
    com.chat: DEBUG
    org.hibernate.SQL: DEBUG
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
    database: postgresql
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: gallampalli
#    password: postgres
    url: jdbc:postgres://ec2-107-21-235-87.compute-1.amazonaws.com:5432/dfkv32e2q2f7ju
    username: hhrfmnuzuryxtr
    password: 49d898113ddb5869838a7ac54c5166c90af8eb33de3f73754a8391ad82d64824